skip_on_cran()

# Create a pointblank agent for testing
agent <-
  create_agent(
    read_fn = ~ small_table,
    actions = action_levels(stop_at = 0.1)
  ) %>%
  col_vals_gt(
    vars(date_time), vars(date),
    na_pass = TRUE
  ) %>%
  col_vals_gt(
    vars(b), vars(g), na_pass = TRUE,
    label = "b > g"
  ) %>%
  col_is_character(
    vars(b, f),
    label = "Verifying character-type columns" 
  ) %>%
  rows_distinct(
    vars(d, e, f),
    label = "Distinct rows across 'd', 'e', and 'f'"
  ) %>%
  col_is_integer(
    vars(a),
    label = "`a` must be an integer",
    active = FALSE
  ) %>%
  interrogate()

work_path <- "./generated_testthat_files"

if (fs::dir_exists(path = work_path)) {
  fs::dir_delete(path = work_path)
}

fs::dir_create(path = work_path)

expect_fixed_match <- function(testthat_file, text) {
  expect_match(testthat_file, text, fixed = TRUE)
}

test_that("a testthat test file can be written using an agent", {
  
  sub_dir <- fs::dir_create(path = "./generated_testthat_files")
  
  write_testthat_file(
    agent = agent,
    name = "testthat",
    path = sub_dir
  )
  
  expect_true(
    fs::file_exists(path = fs::path(work_path, "test-testthat.R"))
  )
  
  testthat_file <- 
    readLines(con = fs::path(work_path, "test-testthat.R")) %>%
    paste0(collapse = "\n")
  
  expect_fixed_match(testthat_file,
    "# Generated by pointblank: do not edit by hand"
  )
  expect_fixed_match(testthat_file,
    "tbl <- small_table"
  )
  expect_fixed_match(testthat_file,
    "test_that(\"values in `date_time` should be > `date`\", {"
  )
  expect_fixed_match(testthat_file,
    "test_that(\"values in `b` should be > `g`\", {"
  )
  expect_fixed_match(testthat_file,
    "test_that(\"column `b` is of type: character\", {"
  )
  expect_fixed_match(testthat_file,
    "test_that(\"column `f` is of type: character\", {"
  )
  expect_fixed_match(testthat_file,
    "test_that(\"entirely distinct rows across `d, e, f`\", {"
  )
  expect_fixed_match(testthat_file,
    "test_that(\"column `a` is of type: integer\", {"
  )
  expect_fixed_match(testthat_file,
    "skip(\"This test is not active.\")"
  )
  expect_fixed_match(testthat_file,
    "# expect_col_is_integer("
  )
  
  # Expect an error if a `read_fn` is not available in agent
  expect_error(
    write_testthat_file(
      agent = remove_read_fn(agent),
      name = "testthat",
      path = sub_dir
    )
  )
  
  # Expect an error if the supplied path does not exist
  expect_error(
    write_testthat_file(
      agent = agent,
      name = "testthat",
      path = "does/not/exist"
    )
  )
  
})

if (fs::dir_exists(path = work_path)) {
  fs::dir_delete(path = work_path)
}
