#' Get a table metadata report from a metadata object
#' 
#' We can get a table metadata report from a metadata object that's generated by
#' the [create_metadata()] function. The report is provided as a **gt** based
#' display table. The amount of metadata shown depends on the extent of that
#' added via the use of the `meta_*()` functions or addition of metadata through
#' direct editing of a **pointblank** YAML file.
#' 
#' @param metadata A metadata object of class `ptblank_metadata`.
#' 
#' @return A **gt** table object.
#' 
#' @examples
#' # Generate a metadata object using
#' # the `small_table` dataset
#' metadata <- create_metadata(small_table)
#' 
#' # This function creates some metadata
#' # without any extra help by profiling
#' # the supplied table object; it adds
#' # the sections: (1) 'table' and
#' # (2) 'columns' and we can print the
#' # object to see the metadata report
#' # metadata
#' 
#' # Alternatively, we can visualize this
#' # metadata into the same report by using
#' # `get_metadata_report()`
#' report <- get_metadata_report(metadata)
#' class(report)
#' 
#' @export
get_metadata_report <- function(metadata) {
  
  # nocov start
  
  time_start <- Sys.time()
  
  if ("metadata_rev" %in% names(metadata)) {
    y <- metadata$metadata_rev
  } else {
    y <- metadata$metadata
  }
  
  if ("meta_label" %in% names(y)) {
    meta_label <- y[["meta_label"]]
    y <- y[names(y) != "meta_label"]
  } else {
    meta_label <- paste0("[", gsub(" ", "|", as.character(Sys.time())), "]")
  }
  meta_label <- create_metadata_label_html(meta_label = meta_label)
  
  meta_columns <- NULL
  meta_rows <- NULL
  
  y_names <- names(y)
  
  priority_items <- c("table",  "columns")
  names_ordered <- sort(base::intersect(y_names, priority_items), decreasing = TRUE)
  names_others <- base::setdiff(y_names, priority_items)
  y <- y[c(names_ordered, names_others)]
  
  # Create empty table  
  tbl <- dplyr::tibble(group = character(0), item = character(0))
  
  if ("table" %in% y_names) {
    
    section <- y[["table"]]
    section_names <- names(section)
    
    if ("name" %in% section_names ||
        "_type" %in% section_names ||
        "type" %in% section_names) {
      
      if ("type" %in% section_names || "_type" %in% section_names) {
        if ("_type" %in% section_names) tbl_src <- section[["_type"]]
        if ("type" %in% section_names) tbl_src <- section[["type"]]
      } else {
        tbl_src <- NA_character_
      }
      
      if ("name" %in% section_names) {
        tbl_name <- section[["name"]]
      } else {
        tbl_name <- NA_character_
      }
      
      table_type_html <-  
        create_table_type_html(
          tbl_src = tbl_src,
          tbl_name = tbl_name
        )
      
      # Remove `name`, `type`, and `_type` from `section_names`
      section_names <- section_names[!(section_names %in% c("name", "type", "_type"))]
    } else {
      table_type_html <- ""
    }
    
    if ("columns" %in% section_names) meta_columns <- as.numeric(section[["columns"]][1])
    if ("_columns" %in% section_names) meta_columns <- as.numeric(section[["_columns"]][1])
    
    if ("rows" %in% section_names) meta_rows <- as.numeric(section[["rows"]][1])
    if ("_rows" %in% section_names) meta_rows <- as.numeric(section[["_rows"]][1])
    
    section_names <- 
      section_names[!(section_names %in% c("columns", "_columns", "rows", "_rows"))]
    
    if (length(section_names) > 0) {
      
      for (s_name in section_names) {
        
        tbl <- 
          add_to_tbl(
            tbl = tbl,
            item = title_text_md(section[s_name], elements = "vertical"),
            group = "Table"
          )
      }
    }
  } else {
    table_type_html <- ""
  }
  
  if ("columns" %in% y_names) {
    
    section <- y[["columns"]]
    column_names <- names(section)
    
    if (length(column_names) > 0) {
      
      for (column in column_names) {
        
        col_meta <- section[[column]]
        col_meta_names <- names(col_meta)
        miniheader_vec <- c()
        
        if (inherits(col_meta, "character")) {
          
          list_item <- 
            list(
              a = paste0("<strong class=\"pb_sub_label\">INFO</strong> ", unlist(col_meta))
            )
          
          names(list_item) <- column
          
          tbl <- 
            add_to_tbl(
              tbl = tbl,
              item = title_text_md(
                item = list_item,
                elements = "vertical",
                title_code = TRUE
              ),
              group = "Columns"
            )
          
        } else {
          
          # TODO: process names in `col_meta` 
          # - specially process `_type` or `type`
          # - specially process `_sql_type` or `sql_type`
          
          if ("_type" %in% col_meta_names ||
              "type" %in% col_meta_names) {
            
            col_type <- NULL
            if ("type" %in% col_meta_names) col_type <- col_meta[["type"]][1]
            if ("_type" %in% col_meta_names) col_type <- col_meta[["_type"]][1]
            col_meta <- col_meta[!(col_meta_names %in% c("type", "_type"))]
            miniheader_vec <- c(miniheader_vec, col_type = col_type)
          }
          
          col_meta <- 
            lapply(col_meta, FUN = function(x) {
              if (length(x) > 1) {
                x <- paste0("\n", paste0("- ", x, "\n", collapse = ""))
              }
              x
            })
          
          list_item <- 
            list(
              a = paste0(
                "<strong class=\"pb_sub_label\">",
                toupper(names(col_meta)),
                "</strong> ", unlist(col_meta)
              )
            )
          
          names(list_item) <- column
          
          tbl <- 
            add_to_tbl(
              tbl = tbl,
              item = title_text_md(
                item = list_item,
                elements = "vertical", 
                title_code = TRUE
              ),
              group = "Columns"
            )
          
          column_escaped <-
            column %>% 
            gsub("(\\(|\\)|\\[|\\]|\\||\\.|\\^|\\?|\\+|\\$|\\*)", "\\\\\\1", .)
          
          row_idx <- 
            which(grepl(paste0("^<code.*?>", column_escaped, "<.*?"), tbl$item))
          
          if (length(miniheader_vec) > 0) {
            tbl$item[[row_idx]] <-
              gsub(
                "(^.*?</code>)(.*)", 
                paste0(
                  "\\1&nbsp;&nbsp;<code class=\"pb_col_type\">",
                  miniheader_vec, "</code>\\2"
                ),
                tbl$item[[row_idx]]
              )
          }
        }
      }
    }
  }
  
  if (length(names_others) > 0) {
    
    for (o_name in names_others) {
      
      o_section <- y[[o_name]]
      section_names <- names(o_section)
      
      if (is.null(section_names) &&
          is.character(o_section) &&
          length(o_section) > 0) {
        
        list_item <- 
          list(
            a = paste0("- ", unlist(o_section))
          )
        
        names(list_item) <- o_name
        
        tbl <- 
          add_to_tbl(
            tbl = tbl,
            item = title_text_md(
              item = list_item,
              elements = "vertical",
              use_title = FALSE
            ),
            group = o_name
          )
      }
      
      for (section in section_names) {
        
        section_meta <- o_section[section]
        
        if (inherits(section_meta, "character")) {
          
          list_item <- 
            list(
              a = paste0("<strong>INFO</strong> ", unlist(section_meta))
            )
          
          names(list_item) <- column
          
          tbl <- 
            add_to_tbl(
              tbl = tbl,
              item = title_text_md(
                item = list_item,
                elements = "vertical",
                title_code = TRUE
              ),
              group = o_name
            )
          
        } else {
          
          tbl <- 
            add_to_tbl(
              tbl = tbl,
              item = title_text_md(
                item = section_meta,
                elements = "vertical",
                use_title = TRUE
              ),
              group = o_name
            )
        }
      }
    }
  }
  
  # Generate table dimensions HTML
  table_dims <- 
    make_table_dims_html(columns = meta_columns, rows = meta_rows)
  
  # Combine label, table type, and table dimensions into
  # a table subtitle <div>
  combined_subtitle <-
    htmltools::tagList(
      htmltools::HTML(meta_label),
      htmltools::tags$div(
        style = htmltools::css(
          height = "25px",
          `margin-top` = "10px"
        ),
        htmltools::HTML(paste0(table_type_html, table_dims))
      ) 
    ) %>% as.character()
  
  time_end <- Sys.time()
  
  # Generate table execution start/end time (and duration)
  # as a table source note
  table_time <- 
    create_table_time_html(
      time_start = time_start,
      time_end = time_end
    )
  
  # Generate a gt table
  gt::gt(
    tbl,
    groupname_col = "group",
    id = "metadata"
  ) %>%
    gt::tab_header(
      title = "Pointblank Metadata",
      subtitle = gt::md(combined_subtitle)
    ) %>%
    gt::tab_source_note(source_note = gt::md(table_time)) %>%
    gt::fmt_markdown(columns = gt::vars(item)) %>%
    gt::cols_width(gt::everything() ~ gt::px(876)) %>%
    gt::tab_options(
      column_labels.hidden = TRUE,
      table.font.size = gt::pct(110)
    ) %>%
    gt::tab_style(
      style = gt::cell_text(
        size = gt::px(24),
        align = "left",
        indent = gt::px(5)
      ),
      locations = gt::cells_title("title")
    ) %>%
    gt::tab_style(
      style = gt::cell_text(
        size = gt::px(12),
        align = "left",
        indent = gt::px(5)
      ),
      locations = gt::cells_title("subtitle")
    ) %>%
    gt::tab_style(
      style = list(
        gt::cell_text(
          color = "#666666",
          weight = "bold",
          transform = "uppercase" 
        ),
        gt::cell_fill(color = "#FCFCFC"),
        gt::cell_borders(
          sides = "bottom",
          color = "#EFEFEF",
          weight = 1
        )
      ),
      locations = gt::cells_row_groups(groups = TRUE)
    ) %>%
    gt::tab_style(
      style = list(
        gt::cell_text(
          color = "#666666",
          size = "smaller",
          indent = gt::px(5)
        ),
        gt::cell_borders(
          sides = "top",
          style = "solid",
          color = "#EFEFEF",
          weight = 1
        )
      ),
      locations = gt::cells_body(columns = gt::everything())
    ) %>%
    gt::opt_table_font(font = gt::google_font("IBM Plex Sans")) %>%
    gt::opt_css(
      css = "
          #metadata p {
            overflow: visible;
            margin-top: 2px;
            margin-left: 0;
            margin-right: 0;
            margin-bottom: 5px;
          }
          #metadata ul {
            list-style-type: square;
            padding-left: 25px;
            margin-top: -4px;
            margin-bottom: 6px;
          }
          #metadata li {
            text-indent: -1px;
          }
          #metadata code {
            font-family: 'IBM Plex Mono', monospace, courier;
            font-size: 13px;
          }
          #metadata .pb_date {
            text-decoration-style: solid;
            text-decoration-color: #9933CC;
            text-decoration-line: underline;
            text-underline-position: under;
            font-variant-numeric: tabular-nums;
            margin-right: 4px;
          }
          #metadata .pb_label {
            border: solid 1px gray;
            padding: 0px 3px 0px 3px;
            margin-left: 2px;
            margin-right: 2px;
          }
          #metadata .pb_sub_label {
            font-size: smaller;
            color: #777777;
          }
          #metadata .pb_col_type {
            font-size: 11px;
          }
          #metadata .gt_sourcenote {
            height: 35px;
            padding: 0
          }
        "
    )
  
  # nocov end
}
