#' Read a **pointblank** YAML file to create a metadata object
#'
#' @description With `meta_yaml_read()` we can read a **pointblank** YAML file
#'   that describes a table metadata (typically generated by the [yaml_write()]
#'   function. What's returned is a new *metadata* object with the metadata
#'   intact. The metadata object can be given more metadata through use of the
#'   `meta_*()` functions.
#' 
#' @param path A path to a **pointblnk** YAML file.
#' 
#' @examples 
#' # We create a pointblank `metadata`
#' # object with `create_metadata()`;
#' # let's use that function with the
#' # `small_table` dataset
#' metadata <- create_metadata(small_table)
#' 
#' # A `metadata` object can be written
#' # to a YAML file by using the
#' # `yaml_write()` function
#' # yaml_write(
#' #   metadata = metadata,
#' #   filename = "metadata-small_table.yml"
#' # )
#' 
#' # The `metadata-small_table.yml` file
#' # looks like this when written
#' 
#' #> meta_label: '[2020-09-06|13:37:38]'
#' #> table:
#' #>   name: small_table
#' #> _columns: 8
#' #> _rows: 13
#' #> _type: tbl_df
#' #> columns:
#' #>   date_time:
#' #>     _type: POSIXct, POSIXt
#' #>   date:
#' #>     _type: Date
#' #>   a:
#' #>     _type: integer
#' #>   b:
#' #>     _type: character
#' #>   c:
#' #>     _type: numeric
#' #>   d:
#' #>     _type: numeric
#' #>   e:
#' #>     _type: logical
#' #>   f:
#' #>     _type: character
#' 
#' # We can add keys and values to
#' # enrich the metadata with more
#' # pertinent information; with some
#' # direct editing of the file we get:
#' 
#' #> meta_label: '[2020-09-06|13:37:38]'
#' #> table:
#' #>   name: small_table
#' #>   _columns: 8
#' #>   _rows: 13
#' #>   _type: tbl_df
#' #> columns:
#' #>   date_time:
#' #>     _type: POSIXct, POSIXt
#' #>     info: Date-time values.
#' #>   date:
#' #>     _type: Date
#' #>     info: Date values (the date part of `date_time`).
#' #>   a:
#' #>     _type: integer
#' #>     info: Small integer values (no missing values).
#' #>   b:
#' #>     _type: character
#' #>     info: Strings with a common pattern.
#' #>   c:
#' #>     _type: numeric
#' #>     info: Small numeric values (contains missing values).
#' #>   d:
#' #>     _type: numeric
#' #>     info: Large numeric values (much greater than `c`).
#' #>   e:
#' #>     _type: logical
#' #>     info: TRUE and FALSE values.
#' #>   f:
#' #>     _type: character
#' #>     info: Strings of the set `"low"`, `"mid"`, and `"high"`.
#' 
#' # We could also have done the same
#' # with the `metadata` object by use of
#' # the  `meta_columns()` function
#' 
#' # The 'metadata-small_table.yml' file
#' # is available in the package through
#' # `system.file()`
#' yml_file <- 
#'   system.file(
#'     "metadata-small_table.yml",
#'     package = "pointblank"
#'   )
#' 
#' # We can read this YAML file back
#' # as a `metadata` object by using
#' # `meta_yaml_read()`
#' metadata <- 
#'   meta_yaml_read(path = yml_file)
#' 
#' class(metadata)
#' 
#' @export
meta_yaml_read <- function(path) {
  
  # Read the YAML file with `yaml::read_yaml()`
  y <- yaml::read_yaml(file = path)
  
  # Perform checks on elements of `y`
  # TODO: Add checks for actions and steps (and other key elements)
  check_meta_yaml_table(y)
  check_meta_yaml_columns(y)
  check_meta_yaml_others(y)

  # Create the metadata list object
  metadata <-
    list(
      read_fn = NULL,
      tbl_name = NULL,
      label = NULL,
      lang = NULL,
      locale = NULL,
      metadata = y
    )
  
  # Assign the class attribute value `ptblank_informant` to
  # the `metadata` object
  attr(metadata, "class") <- "ptblank_informant"
  
  metadata
}

check_meta_yaml_table <- function(y) {
  
  # If `table` is present, perform a few validations on that component
  if ("table" %in% names(y)) {
    
    # Validate that 2nd-level elements have unique names
    if (any(duplicated(names(y[["table"]])))) {
      stop("Duplicate column names provided in `table`.", call. = FALSE)
    }
    
    # Get component names of `table`
    table_names <- names(y[["table"]])
    
    # Validate that there are only character vectors inside `table`
    checks <- 
      lapply(
        table_names,
        FUN = function(x) {
          x_names <- names(y[["table"]][x])
          
          for (z in x_names) {
            if (is.list(y[["table"]][[z]])) {
              stop("All subcomponents inside of `table` should be a character vector.",
                   call. = FALSE)
            }
          }
        }
      )
  }
}

check_meta_yaml_columns <- function(y) {
  
  # If `columns` is present, perform a few validations on that component
  if ("columns" %in% names(y)) {
    
    # Validate that 2nd-level elements have unique names
    if (any(duplicated(names(y[["columns"]])))) {
      stop("Duplicate column names provided in `columns`.", call. = FALSE)
    }
    
    # Get listed column names
    column_names <- names(y[["columns"]])
    
    # Validate that there is no more than only a single level below
    # the column names
    checks <- 
      lapply(
        column_names,
        FUN = function(x) {
          x_names <- names(y[["columns"]][x])
          
          for (z in x_names) {
            
            if (is.list(y[["columns"]][[z]])) {
              if (!all(unname(unlist(lapply(y[["columns"]][[z]], is.character))))) {
                stop("All components inside of `columns/", z, "` should either be text or text under a single heading.",
                     call. = FALSE)
              }
            }
          }
        }
      )
  }
}

check_meta_yaml_others <- function(y) {
  
  # If any other items are present, perform a few validations on those
  exclusions <- c("table", "columns", "actions", "steps")
  other_names <- base::setdiff(names(y), exclusions)
  
  if (length(other_names) > 0) {
    
    # Validate that there is no more than only a single level below
    # the column names
    checks <- 
      lapply(
        other_names,
        FUN = function(x) {
          
          if (is.list(y[[x]])) {
            
            if (any(unname(unlist(lapply(y[[x]], Negate(is.character)))))) {
              
              idx <- which(unname(unlist(lapply(y[[x]], Negate(is.character)))))
              
              stop("All components inside `",x, "/", names(y[[x]][idx]),
                   "` should be a character vector.",
                   call. = FALSE)
            }
            
          } else if (!is.list(y[[x]])) {
            if (!is.character(y[[x]])) {
              stop("The component inside `", x, "` should be a character vector.",
                   call. = FALSE)
            }
          }
        }
      )
  }
}

add_to_tbl <- function(tbl, item, group) {
  dplyr::bind_rows(tbl, dplyr::tibble(group = group, item = item))
}

title_text_md <- function(item,
                          use_title = TRUE,
                          title_level = 4,
                          title_code = FALSE,
                          elements = "vertical") {
  
  title <- names(item)
  item <- unname(unlist(item))
  
  # Process item with text transformers
  for (i in seq_along(item)) {
    
    # Dates
    if (grepl("\\([1-2][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]\\)", item[i])) {
      
      for (j in 1:10) {
        item[i] <- 
          gsub(
            "(.*)\\(([1-2][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9])\\)(.*)",
            "\\1<span class=\"pb_date\">\\2</span>\\3",
            item[i]
          )
      }
    }
    
    # Labels
    if (grepl("\\([A-Z][A-Z_]{1,}[A-Z]\\)", item[i])) {
      
      for (j in 1:10) {
        item[i] <-
          gsub(
            "(.*)\\(([A-Z][A-Z_]{1,}[A-Z])\\)(.*)",
            "\\1<span class=\"pb_label\">\\2</span>\\3",
            item[i]
          )
      }
    }
  }
  
  if (elements == "vertical") {
    
    item <- paste(item, collapse = "\n\n")
    
    if (use_title) {
      
      if (!title_code) {
        title <- gsub("_", " ", toupper(title))
      }
      
      item <- 
        paste0(
          "<",
          ifelse(title_code, "code", "h"),
          ifelse(title_code, "", as.character(title_level)), " ",
          "style=\"margin-bottom:5px;",
          ifelse(
            title_code,
            paste0(
              "font-weight:bold;line-height:2em;",
              "border:solid 1px #499FFE;",
              "padding:2px 8px 3px 8px;background-color:#FAFAFA;"
            ),
            ""
          ),
          "\">",
          title, "</", ifelse(title_code, "code", "h"),
          ifelse(title_code, "", as.character(title_level)), ">\n\n",
          item
        )
    }
    
  } else if (elements == "horizontal") {
    
    item <- paste(item, collapse = " &mdash; ")
    
    if (use_title) {
      
      if (!title_code) {
        title <- gsub("_", " ", toupper(title))
      }
      
      item <- 
        paste0(
          "<span style=\"font-size:1.17em;font-weight:bold;\">",
          ifelse(title_code, "<code style=\"font-weight:bold;margin-bottom:2px;\">", ""),
          title,
          ifelse(title_code, "</code>", ""),
          "</span>&nbsp;&nbsp;",
          item
        )
    }
  }
  
  item
}

create_metadata_label_html <- function(meta_label) {
  
  htmltools::tags$span(
    meta_label,
    style = htmltools::css(
      `text-decoration-style` = "solid",
      `text-decoration-color` = "#ADD8E6",
      `text-decoration-line` = "underline",
      `text-underline-position` = "under",
      color = "#333333",
      `font-variant-numeric` = "tabular-nums",
      `padding-left` = "4px",
      `margin-right` = "5px",
      `padding-right` = "2px"
    )
  ) %>% as.character()
}

make_table_dims_html <- function(columns = NULL, rows = NULL) {
  
  if (is.null(columns) && is.null(rows)) {
    return("")
  }
  
  columns <- columns %||% "&mdash;"
  rows <- rows %||% "&mdash;"
  
  as.character(
    htmltools::tagList(
      htmltools::tags$span(
        "ROWS",
        style = htmltools::css(
          `background-color` = "#eecbff",
          color = "#333333",
          padding = "0.5em 0.5em",
          position = "inherit",
          `text-transform` = "uppercase",
          margin = "5px 0px 5px 5px",
          `font-weight` = "bold",
          border = paste0("solid 1px #eecbff"),
          padding = "2px 15px 2px 15px",
          `font-size` = "smaller"
        )
      ),
      htmltools::tags$span(
        htmltools::HTML(rows),
        style = htmltools::css(
          `background-color` = "none",
          color = "#333333",
          padding = "0.5em 0.5em",
          position = "inherit",
          margin = "5px 0px 5px -4px",
          `font-weight` = "bold",
          border = paste0("solid 1px #eecbff"),
          padding = "2px 15px 2px 15px",
          `font-size` = "smaller"
        )
      ),
      htmltools::tags$span(
        "COLUMNS",
        style = htmltools::css(
          `background-color` = "#BDE7B4",
          color = "#333333",
          padding = "0.5em 0.5em",
          position = "inherit",
          `text-transform` = "uppercase",
          margin = "5px 0px 5px 1px",
          `font-weight` = "bold",
          border = paste0("solid 1px #BDE7B4"),
          padding = "2px 15px 2px 15px",
          `font-size` = "smaller"
        )
      ),
      htmltools::tags$span(
        htmltools::HTML(columns),
        style = htmltools::css(
          `background-color` = "none",
          color = "#333333",
          padding = "0.5em 0.5em",
          position = "inherit",
          margin = "5px 0px 5px -4px",
          `font-weight` = "bold",
          border = paste0("solid 1px #BDE7B4"),
          padding = "2px 15px 2px 15px",
          `font-size` = "smaller"
        )
      )
    )
  )
}
